# version: '3.9'

services:
  yolo:
    build: .
    container_name: yolo11n-gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      # Для сохранения весов модели
      - ./models:/root/.cache/torch/hub/checkpoints
    ports:
      - "7860:7860"  # Если используется Gradio/FastAPI
    stdin_open: true
    tty: true
    # Для увеличения доступной памяти (опционально)
    shm_size: '5gb'